"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.x
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Cargar variables de entorno desde .env (si existe)
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# -------------------------
# Básico / Entorno
# -------------------------
SECRET_KEY = os.getenv("SECRET_KEY", "dev-unsafe")  # en prod, ponelo en .env
DEBUG = os.getenv("DEBUG", "True") == "True"
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")

# -------------------------
# Apps
# -------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Nuestra app
    'lms',
]

# -------------------------
# Middleware
# -------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

# -------------------------
# Templates
# -------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 👇 importante para que tome templates globales como registration/login.html
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,     # carga lms/templates/...
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# -------------------------
# Base de datos (SQLite dev)
# -------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# -------------------------
# Password validators
# -------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# -------------------------
# Internacionalización
# -------------------------
LANGUAGE_CODE = 'es-ar'  # podés dejar 'en-us' si preferís
TIME_ZONE = 'America/Argentina/Buenos_Aires'
USE_I18N = True
USE_TZ = True

# -------------------------
# Static
# -------------------------
STATIC_URL = 'static/'
# (opcional en dev)
# STATICFILES_DIRS = [BASE_DIR / 'static']

# -------------------------
# Auth redirects (login/logout)
# -------------------------
LOGIN_URL = 'login'              # /login/ de django.contrib.auth.urls
LOGIN_REDIRECT_URL = 'lms:home'  # a dónde ir después de loguear
LOGOUT_REDIRECT_URL = 'lms:home' # a dónde ir después de salir

# -------------------------
# Default PK
# -------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
